#!/bin/sh
module="memryx_pcie"
device="memryx"
mode="644"

/sbin/insmod ./$module.ko $* || exit 1

rm -f  /dev/${device}[0-3]

major=$(awk "$2=  =\"$module\" {print \$1}" /proc/devices)

/usr/bin/mknod /dev/${device}0 c $major 0
/usr/bin/mknod /dev/${device}1 c $major 1
/usr/bin/mknod /dev/${device}2 c $major 2
/usr/bin/mknod /dev/${device}3 c $major 3


group="staff"
grep -q '^staff:' /etc/group || group="wheel"
chgrp $group /dev/${device}[0-3]
chmod $mode /dev/${device}[0-3]
